#!/usr/bin/env python3
"""Sync the rust-delivery agent system (agents, skills, orchestrator) into a Rust project.

The workspace `templates/` folder is the only source. This engine renders it for Claude Code and Codex,
applies the project's own configuration and extensions, and keeps the result current.

Commands:
  check                        validate the templates themselves
  install PROJECT [--tools claude,codex] [--name NAME]
                               seed .delivery/, render everything, register the SessionStart hooks
  sync [PROJECT] [--dry-run]   render from the templates now (also adopts updates in pinned mode)
  session-start --tool TOOL    SessionStart hook entry point: quiet when nothing changed, never fails
  status [PROJECT]             installed and available versions, pending changes, hand edits
  verify [PROJECT]             exit 1 unless the installation is complete, unedited, and current
  sync-all ROOT [--dry-run]    sync every installed project directly under ROOT
  new agent|skill NAME [PROJECT]
                               scaffold a project-local component in .delivery/local/

PROJECT defaults to the project that contains this copy of the engine, or else the current directory.
Exit status: 0 on success, 1 on findings or errors, 2 on bad usage. Needs Python 3.11 or newer, and
nothing outside the standard library.
"""

from __future__ import annotations

import argparse
import contextlib
import datetime as dt
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

SYSTEM = "rust-delivery"
TOOLS = ("claude", "codex")

DELIVERY_DIR = ".delivery"
ENGINE_REL = ".delivery/sync.py"
CHECKPOINT_REL = ".delivery/checkpoint.py"
CONFIG_REL = ".delivery/project.toml"
LOCK_REL = ".delivery/sync-lock.json"
EXTENSIONS_REL = ".delivery/extensions"
LOCAL_REL = ".delivery/local"
BACKUPS_REL = ".delivery/backups"
MUTEX_REL = ".delivery/.sync.lock"
TEMPLATES_ENV = "RUST_DELIVERY_TEMPLATES"
REEXEC_ENV = "RUST_DELIVERY_REEXEC"

BLOCK_BEGIN = (
    "<!-- BEGIN rust-delivery: generated from the workspace templates at every session start. "
    "Do not edit inside this block; use .delivery/extensions/orchestrator.md. -->"
)
BLOCK_END = "<!-- END rust-delivery -->"
BLOCK_RE = re.compile(r"<!-- BEGIN rust-delivery\b.*?-->\n?(.*?)<!-- END rust-delivery -->\n?", re.DOTALL)
HOOK_MARKER = ".delivery/sync.py"
HOOK_MATCHER = "startup|resume|clear"
HOOK_TIMEOUT = 60


def hook_command(tool: str) -> str:
    """The SessionStart command for one tool.

    Hooks run in the session's working directory, which may be below the project root, and Codex has no
    project-dir variable. So the command walks up to the nearest installed engine and does nothing when
    there is none. It must stay byte-identical across releases: Codex asks the user to trust a hook
    again whenever its hash changes.
    """
    return (
        "python3 -c \"import pathlib,runpy,sys; c=pathlib.Path.cwd(); "
        "e=next((d/'.delivery/sync.py' for d in (c,*c.parents) if (d/'.delivery/sync.py').is_file()),None); "
        f"sys.argv=['sync.py','session-start','--tool','{tool}']; "
        "e and runpy.run_path(str(e),run_name='__main__')\""
    )


NAME_RE = re.compile(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")
VAR_RE = re.compile(r"\{\{\s*([a-z_][a-z0-9_]*(?:\.[a-z_][a-z0-9_]*)*)\s*\}\}")
BLOCK_SECTION_RE = re.compile(r"^\{\{#(claude|codex)\}\}\n(.*?)^\{\{/\1\}\}\n", re.DOTALL | re.MULTILINE)
INLINE_SECTION_RE = re.compile(r"\{\{#(claude|codex)\}\}(.*?)\{\{/\1\}\}", re.DOTALL)
IGNORED_NAMES = {"__pycache__", ".DS_Store", "Thumbs.db"}
GENERATED_NOTE = "Generated by rust-delivery from the workspace templates. Do not edit this file"

# Frontmatter keys passed through to each tool. Anything else is reported, so typos surface at check time.
CLAUDE_AGENT_KEYS = (
    "tools", "disallowedTools", "model", "effort", "permissionMode", "maxTurns", "memory",
    "isolation", "background", "color",
)
CLAUDE_SKILL_KEYS = (
    "when_to_use", "argument-hint", "arguments", "disable-model-invocation", "user-invocable",
    "allowed-tools", "disallowed-tools", "model", "effort", "context", "agent", "paths",
)
CODEX_AGENT_KEYS = ("nickname_candidates", "model", "model_reasoning_effort", "sandbox_mode")
CODEX_SKILL_KEYS = ("display_name", "allow_implicit_invocation")
AGENT_KEYS = {"name", "description", "summary", "stage", "skills", "claude", "codex"}
SKILL_KEYS = {"name", "description", "summary", "claude", "codex"}
CONFIG_KEYS = {"schema", "project", "sync", "commands", "vars", "agents", "skills", "routes"}
MANIFEST_KEYS = {
    "schema", "system", "defaults", "tools", "orchestrator", "partials", "seeds", "managed",
    "agents", "skills",
}
SYNC_KEYS = {"mode", "tools"}
ROUTE_KEYS = {"trigger", "agent", "after", "gate"}
AGENT_OVERRIDE_KEYS = {"enabled", "extra_skills", "claude", "codex"}
SKILL_OVERRIDE_KEYS = {"enabled", "claude", "codex"}
CONTEXT_KEY_RE = re.compile(r"^[a-z_][a-z0-9_]*$")


class SyncError(Exception):
    """A problem that stops a sync before anything is written."""


# --------------------------------------------------------------------------------------------------
# Small utilities


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def utc_stamp() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")


def read_toml(path: Path) -> dict:
    try:
        return tomllib.loads(path.read_text(encoding="utf-8"))
    except OSError as error:
        raise SyncError(f"{path}: unreadable ({error.strerror})") from error
    except tomllib.TOMLDecodeError as error:
        raise SyncError(f"{path}: invalid TOML ({error})") from error


def atomic_write(path: Path, data: bytes, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    temporary.write_bytes(data)
    if executable:
        temporary.chmod(0o755)
    os.replace(temporary, path)


def inside(root: Path, relative: str) -> Path:
    target = (root / relative).resolve()
    if not target.is_relative_to(root.resolve()):
        raise SyncError(f"{relative}: resolves outside {root}")
    return target


def normalize_text(text: str) -> str:
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip("\n") + "\n"


def yaml_scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(str(value), ensure_ascii=False)


def yaml_mapping(mapping: dict, indent: int = 0) -> str:
    lines, pad = [], " " * indent
    for key, value in mapping.items():
        if isinstance(value, dict):
            lines.append(f"{pad}{key}:")
            lines.append(yaml_mapping(value, indent + 2).rstrip("\n"))
        elif isinstance(value, list):
            lines.append(f"{pad}{key}:")
            lines.extend(f"{pad}  - {yaml_scalar(item)}" for item in value)
        else:
            lines.append(f"{pad}{key}: {yaml_scalar(value)}")
    return "\n".join(lines) + "\n"


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def toml_multiline(value: str) -> str:
    escaped = value.replace("\\", "\\\\")
    escaped = re.sub(r'"(?="")', '\\"', escaped)
    escaped = re.sub(r"[\x00-\x08\x0b-\x1f\x7f]", lambda m: f"\\u{ord(m.group(0)):04x}", escaped)
    return f'"""\n{escaped}"""'


def toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    return toml_string(str(value))


def md_cell(text: str) -> str:
    return " ".join(str(text).split()).replace("|", "\\|")

def require_mapping(value, where: str) -> dict:
    if not isinstance(value, dict):
        raise SyncError(f"{where}: expected a table")
    return value


def require_list(value, where: str) -> list:
    if not isinstance(value, list):
        raise SyncError(f"{where}: expected an array")
    return value


def template_source(root: Path, relative, where: str) -> Path:
    if not isinstance(relative, str) or not relative:
        raise SyncError(f"{where}: source must be a non-empty relative path")
    path = (root / relative).resolve()
    if not path.is_relative_to(root.resolve()):
        raise SyncError(f"{where}: source {relative!r} resolves outside {root}")
    return path


# --------------------------------------------------------------------------------------------------
# Templates


def split_frontmatter(text: str, where: str) -> tuple[dict, str]:
    if not text.startswith("+++\n"):
        raise SyncError(f"{where}: must begin with a +++ TOML frontmatter block")
    end = text.find("\n+++\n", 3)
    if end < 0:
        raise SyncError(f"{where}: frontmatter is not closed with +++")
    try:
        meta = tomllib.loads(text[4:end + 1])
    except tomllib.TOMLDecodeError as error:
        raise SyncError(f"{where}: invalid frontmatter ({error})") from error
    return meta, text[end + 5:].lstrip("\n")


def render(text: str, context: dict, tool: str | None, where: str) -> str:
    for pattern in (BLOCK_SECTION_RE, INLINE_SECTION_RE):
        text = pattern.sub(lambda m: m.group(2) if m.group(1) == tool else "", text)
    if "{{#" in text or "{{/" in text:
        raise SyncError(f"{where}: unbalanced or nested {{{{#tool}}}} section")

    def substitute(match: re.Match) -> str:
        value = context
        for part in match.group(1).split("."):
            if not isinstance(value, dict) or part not in value:
                line = text.count("\n", 0, match.start()) + 1
                raise SyncError(f"{where}:{line}: unknown template variable {{{{{match.group(1)}}}}}")
            value = value[part]
        if isinstance(value, (dict, list)):
            raise SyncError(f"{where}: template variable {{{{{match.group(1)}}}}} is not a scalar")
        return str(value)

    return VAR_RE.sub(substitute, text)


@dataclass
class Component:
    kind: str  # "agent" or "skill"
    name: str
    origin: str  # "template" or "local"
    source: Path  # agent: the .md file; skill: the directory
    meta: dict
    body: str

    @property
    def label(self) -> str:
        return f"{self.kind} {self.name}"


def load_component(kind: str, name: str, origin: str, source: Path) -> Component:
    entry = source if kind == "agent" else source / "SKILL.md"
    if not entry.is_file():
        raise SyncError(f"{entry}: missing")
    meta, body = split_frontmatter(entry.read_text(encoding="utf-8"), str(entry))
    allowed = AGENT_KEYS if kind == "agent" else SKILL_KEYS
    unknown = set(meta) - allowed
    if unknown:
        raise SyncError(f"{entry}: unknown frontmatter keys {sorted(unknown)}")
    for tool in TOOLS:
        if tool in meta and not isinstance(meta[tool], dict):
            raise SyncError(f"{entry}: [{tool}] must be a table")
    if meta.get("name") != name:
        raise SyncError(f"{entry}: frontmatter name {meta.get('name')!r} does not match {name!r}")
    if not NAME_RE.match(name) or len(name) > 64:
        raise SyncError(f"{entry}: name {name!r} must be lowercase words joined by hyphens, at most 64 characters")
    if kind == "agent":
        stage = meta.get("stage")
        if not isinstance(stage, str) or not stage.strip():
            raise SyncError(f"{entry}: stage is required")
        assigned = meta.get("skills", [])
        if not isinstance(assigned, list) or any(not isinstance(item, str) for item in assigned):
            raise SyncError(f"{entry}: skills must be an array of skill names")
        if len(assigned) != len(set(assigned)):
            raise SyncError(f"{entry}: skills contains a duplicate")
        for skill_name in assigned:
            if not NAME_RE.match(skill_name):
                raise SyncError(f"{entry}: invalid skill name {skill_name!r}")
    description = meta.get("description")
    if not isinstance(description, str) or not description.strip():
        raise SyncError(f"{entry}: description is required")
    if len(description) > 1024:
        raise SyncError(f"{entry}: description is {len(description)} characters; the limit is 1024")
    if "\n" in description:
        raise SyncError(f"{entry}: description must be one line")
    summary = meta.get("summary", "")
    if not isinstance(summary, str) or not summary.strip() or len(summary) > 100 or "\n" in summary:
        raise SyncError(f"{entry}: summary is required and must be one line of at most 100 characters")
    if origin == "local":
        unfinished = [description, summary, meta.get("stage", ""), body.lstrip()]
        if any(isinstance(value, str) and value.startswith(("TODO:", "# TODO:")) for value in unfinished):
            raise SyncError(f"{entry}: finish the scaffold TODOs before syncing")
    return Component(kind, name, origin, source, meta, body)


@dataclass
class Templates:
    root: Path
    manifest: dict
    agents: list[Component]
    skills: list[Component]
    orchestrator: str
    partials: dict[str, str]

    @property
    def version(self) -> str:
        return self.manifest["system"]["version"]

    @property
    def engine(self) -> Path:
        return self.root / self.manifest["system"]["engine"]


def load_templates(root: Path) -> Templates:
    root = root.resolve()
    manifest = read_toml(root / "manifest.toml")
    unknown = set(manifest) - MANIFEST_KEYS
    if unknown:
        raise SyncError(f"manifest.toml: unknown tables or keys {sorted(unknown)}")

    system = require_mapping(manifest.get("system"), "manifest.toml [system]")
    if manifest.get("schema") != 1 or system.get("name") != SYSTEM:
        raise SyncError(f"{root / 'manifest.toml'}: not a schema 1 {SYSTEM} manifest")
    if not isinstance(system.get("version"), str) or not system["version"].strip():
        raise SyncError("manifest.toml: [system] version must be a non-empty string")
    engine_path = template_source(root, system.get("engine"), "manifest.toml [system]")
    if not engine_path.is_file():
        raise SyncError(f"{engine_path}: missing engine")

    defaults = require_mapping(manifest.get("defaults", {}), "manifest.toml [defaults]")
    unknown_defaults = set(defaults) - {"project", "commands"}
    if unknown_defaults:
        raise SyncError(f"manifest.toml: [defaults] has unknown tables {sorted(unknown_defaults)}")
    for table in ("project", "commands"):
        values = require_mapping(defaults.get(table, {}), f"manifest.toml [defaults.{table}]")
        for key, value in values.items():
            if not CONTEXT_KEY_RE.match(key) or not isinstance(value, str):
                raise SyncError(f"manifest.toml: [defaults.{table}] {key!r} must be a string with a template-safe key")

    tools = require_mapping(manifest.get("tools"), "manifest.toml [tools]")
    unknown_tools = set(tools) - set(TOOLS)
    if unknown_tools:
        raise SyncError(f"manifest.toml: unsupported tools {sorted(unknown_tools)}")
    required_tool_keys = {"name", "instructions", "agents_dir", "skills_dir", "hook_file", "skill_prefix"}
    for tool in TOOLS:
        definition = require_mapping(tools.get(tool), f"manifest.toml [tools.{tool}]")
        missing = required_tool_keys - set(definition)
        if missing:
            raise SyncError(f"manifest.toml: [tools.{tool}] is missing {sorted(missing)}")
        for key in required_tool_keys:
            if not isinstance(definition[key], str) or not definition[key]:
                raise SyncError(f"manifest.toml: [tools.{tool}] {key} must be a non-empty string")
        for key in ("instructions", "agents_dir", "skills_dir", "hook_file"):
            inside(root, definition[key])
        limit = definition.get("instructions_max_bytes")
        if limit is not None and (not isinstance(limit, int) or isinstance(limit, bool) or limit <= 0):
            raise SyncError(f"manifest.toml: [tools.{tool}] instructions_max_bytes must be a positive integer")

    agents, skills, seen = [], [], set()
    for kind, key in (("agent", "agents"), ("skill", "skills")):
        entries = require_list(manifest.get(key, []), f"manifest.toml [[{key}]]")
        for index, item in enumerate(entries, 1):
            entry = require_mapping(item, f"manifest.toml [[{key}]] {index}")
            extra = set(entry) - {"name", "source"}
            if extra:
                raise SyncError(f"manifest.toml: [[{key}]] {index} has unknown keys {sorted(extra)}")
            name = entry.get("name", "")
            if (kind, name) in seen:
                raise SyncError(f"manifest.toml: {kind} {name!r} is listed twice")
            seen.add((kind, name))
            source = template_source(root, entry.get("source"), f"manifest.toml [[{key}]] {index}")
            component = load_component(kind, name, "template", source)
            (agents if kind == "agent" else skills).append(component)

    orchestrator = require_mapping(manifest.get("orchestrator"), "manifest.toml [orchestrator]")
    if set(orchestrator) != {"source"}:
        raise SyncError("manifest.toml: [orchestrator] must contain only source")
    orchestrator_path = template_source(root, orchestrator["source"], "manifest.toml [orchestrator]")
    if not orchestrator_path.is_file():
        raise SyncError(f"{orchestrator_path}: missing")

    partials = {}
    for key, relative in require_mapping(manifest.get("partials", {}), "manifest.toml [partials]").items():
        if not CONTEXT_KEY_RE.match(key):
            raise SyncError(f"manifest.toml: partial key {key!r} is not template-safe")
        path = template_source(root, relative, f"manifest.toml [partials] {key}")
        if not path.is_file():
            raise SyncError(f"{path}: missing partial {key!r}")
        partials[key] = path.read_text(encoding="utf-8")
    for table in ("seeds", "managed"):
        mapping = require_mapping(manifest.get(table, {}), f"manifest.toml [{table}]")
        for target, relative in mapping.items():
            inside(root, target)
            path = template_source(root, relative, f"manifest.toml [{table}] {target}")
            if not path.is_file():
                raise SyncError(f"manifest.toml [{table}] {target}: source {relative} is missing")
    return Templates(root, manifest, agents, skills, orchestrator_path.read_text(encoding="utf-8"), partials)


def is_templates_root(path: Path) -> bool:
    try:
        manifest = tomllib.loads((path / "manifest.toml").read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return False
    return manifest.get("system", {}).get("name") == SYSTEM


def find_templates(project: Path, lock: dict | None) -> Path | None:
    candidates = []
    if os.environ.get(TEMPLATES_ENV):
        candidates.append(Path(os.environ[TEMPLATES_ENV]))
    own = Path(__file__).resolve().parent.parent
    candidates.append(own)
    if lock and lock.get("source"):
        candidates.append(project / lock["source"])
    candidates.extend(directory / "templates" for directory in (project, *project.parents))
    for candidate in candidates:
        if is_templates_root(candidate):
            return candidate.resolve()
    return None


# --------------------------------------------------------------------------------------------------
# Project configuration


@dataclass
class Config:
    raw: dict
    project: dict
    tools: list[str]
    mode: str
    commands: dict
    variables: dict
    agents: dict
    skills: dict
    routes: list[dict]


def load_config(project: Path, templates: Templates) -> Config:
    path = project / CONFIG_REL
    if path.exists() and not path.is_file():
        raise SyncError(f"{CONFIG_REL}: expected a file")
    raw = read_toml(path) if path.is_file() else {}
    unknown = set(raw) - CONFIG_KEYS
    if unknown:
        raise SyncError(f"{CONFIG_REL}: unknown tables or keys {sorted(unknown)}")
    if raw and raw.get("schema") != 1:
        raise SyncError(f"{CONFIG_REL}: schema must be 1")

    defaults = templates.manifest.get("defaults", {})
    tables = {}
    for table in ("project", "commands", "vars", "agents", "skills"):
        tables[table] = require_mapping(raw.get(table, {}), f"{CONFIG_REL}: [{table}]")
    sync = require_mapping(raw.get("sync", {}), f"{CONFIG_REL}: [sync]")
    unknown_sync = set(sync) - SYNC_KEYS
    if unknown_sync:
        raise SyncError(f"{CONFIG_REL}: [sync] has unknown keys {sorted(unknown_sync)}")

    tools = require_list(sync.get("tools", list(TOOLS)), f"{CONFIG_REL}: [sync] tools")
    if (not tools or any(not isinstance(tool, str) or tool not in TOOLS for tool in tools)
            or len(tools) != len(set(tools))):
        raise SyncError(f"{CONFIG_REL}: [sync] tools must be a non-empty, duplicate-free subset of {list(TOOLS)}")
    mode = sync.get("mode", "auto")
    if mode not in ("auto", "pinned"):
        raise SyncError(f"{CONFIG_REL}: [sync] mode must be 'auto' or 'pinned'")

    for table in ("project", "commands", "vars"):
        for key, value in tables[table].items():
            if not CONTEXT_KEY_RE.match(key):
                raise SyncError(f"{CONFIG_REL}: [{table}] key {key!r} is not usable in a template variable")
            if not isinstance(value, str):
                raise SyncError(f"{CONFIG_REL}: [{table}] {key} must be a string")
            if table != "vars" and not value.strip():
                raise SyncError(f"{CONFIG_REL}: [{table}] {key} must not be empty")

    for kind, overrides, allowed in (
        ("agent", tables["agents"], AGENT_OVERRIDE_KEYS),
        ("skill", tables["skills"], SKILL_OVERRIDE_KEYS),
    ):
        for name, value in overrides.items():
            if not NAME_RE.match(name):
                raise SyncError(f"{CONFIG_REL}: invalid {kind} name {name!r}")
            override = require_mapping(value, f"{CONFIG_REL}: [{kind}s.{name}]")
            extra = set(override) - allowed
            if extra:
                raise SyncError(f"{CONFIG_REL}: [{kind}s.{name}] has unknown keys {sorted(extra)}")
            if "enabled" in override and not isinstance(override["enabled"], bool):
                raise SyncError(f"{CONFIG_REL}: [{kind}s.{name}] enabled must be a boolean")
            for tool in TOOLS:
                if tool in override:
                    require_mapping(override[tool], f"{CONFIG_REL}: [{kind}s.{name}.{tool}]")
            if kind == "agent" and "extra_skills" in override:
                assigned = require_list(override["extra_skills"], f"{CONFIG_REL}: [agents.{name}] extra_skills")
                if (any(not isinstance(item, str) or not NAME_RE.match(item) for item in assigned)
                        or len(assigned) != len(set(assigned))):
                    raise SyncError(
                        f"{CONFIG_REL}: [agents.{name}] extra_skills must contain unique skill names"
                    )

    routes = require_list(raw.get("routes", []), f"{CONFIG_REL}: [[routes]]")
    for index, value in enumerate(routes, 1):
        route = require_mapping(value, f"{CONFIG_REL}: route {index}")
        missing, extra = ROUTE_KEYS - set(route), set(route) - ROUTE_KEYS
        if missing:
            raise SyncError(f"{CONFIG_REL}: route {index} is missing {sorted(missing)}")
        if extra:
            raise SyncError(f"{CONFIG_REL}: route {index} has unknown keys {sorted(extra)}")
        for key in ROUTE_KEYS:
            if not isinstance(route[key], str) or not route[key].strip():
                raise SyncError(f"{CONFIG_REL}: route {index} {key} must be a non-empty string")

    project_vars = {**defaults.get("project", {}), **tables["project"]}
    commands = {**defaults.get("commands", {}), **tables["commands"]}
    return Config(raw, project_vars, tools, mode, commands, tables["vars"], tables["agents"],
                  tables["skills"], routes)


def load_local_components(project: Path) -> tuple[list[Component], list[Component]]:
    agents, skills = [], []
    agent_dir, skill_dir = project / LOCAL_REL / "agents", project / LOCAL_REL / "skills"
    if agent_dir.is_dir():
        for path in sorted(agent_dir.glob("*.md")):
            agents.append(load_component("agent", path.stem, "local", path))
    if skill_dir.is_dir():
        for path in sorted(p for p in skill_dir.iterdir() if p.is_dir() and p.name not in IGNORED_NAMES):
            skills.append(load_component("skill", path.name, "local", path))
    return agents, skills


def select_components(templates: Templates, config: Config, project: Path) -> tuple[list[Component], list[Component]]:
    local_agents, local_skills = load_local_components(project)
    selected = []
    for kind, base, local, overrides in (
        ("agent", templates.agents, local_agents, config.agents),
        ("skill", templates.skills, local_skills, config.skills),
    ):
        names = {component.name for component in base}
        for name, override in overrides.items():
            if name not in names and name not in {component.name for component in local}:
                raise SyncError(f"{CONFIG_REL}: [{kind}s.{name}] names no {kind}")
            extra = set(override) - {"enabled", "extra_skills", "claude", "codex"}
            if extra:
                raise SyncError(f"{CONFIG_REL}: [{kind}s.{name}] has unknown keys {sorted(extra)}")
        enabled = [c for c in base if overrides.get(c.name, {}).get("enabled", True)]
        enabled_names = {c.name for c in enabled}
        for component in local:
            if component.name in enabled_names:
                raise SyncError(
                    f"{LOCAL_REL}/{kind}s/{component.name}: collides with the template {kind}; "
                    f"disable the template one in {CONFIG_REL} first"
                )
        selected.append(enabled + local)
    agents, skills = selected
    skill_names = {skill.name for skill in skills}
    for agent in agents:
        for skill in agent_skill_names(agent, config):
            if skill not in skill_names:
                raise SyncError(f"agent {agent.name} needs skill {skill!r}, which is disabled or missing")
    agent_names = {agent.name for agent in agents}
    for route in config.routes:
        if route["agent"] not in agent_names:
            raise SyncError(f"{CONFIG_REL}: route agent {route['agent']!r} is disabled or missing")
    for kind, components in (("agents", agents), ("skills", skills)):
        folder = project / EXTENSIONS_REL / kind
        known = {c.name for c in components if c.origin == "template"}
        if folder.is_dir():
            for path in sorted(folder.glob("*.md")):
                if path.stem not in known:
                    raise SyncError(
                        f"{EXTENSIONS_REL}/{kind}/{path.name}: names no enabled template {kind[:-1]} "
                        f"(edit a project-local {kind[:-1]} directly in {LOCAL_REL}/{kind}/)"
                    )
    return agents, skills


def agent_skill_names(agent: Component, config: Config) -> list[str]:
    names = list(agent.meta.get("skills", []))
    for extra in config.agents.get(agent.name, {}).get("extra_skills", []):
        if extra not in names:
            names.append(extra)
    return names


def tool_meta(component: Component, config: Config, tool: str) -> dict:
    overrides = (config.agents if component.kind == "agent" else config.skills).get(component.name, {})
    return {**component.meta.get(tool, {}), **overrides.get(tool, {})}


# --------------------------------------------------------------------------------------------------
# Rendering


@dataclass
class Plan:
    files: dict[str, bytes] = field(default_factory=dict)  # fully managed files
    blocks: dict[str, str] = field(default_factory=dict)  # managed blocks inside instruction files
    hooks: dict[str, str] = field(default_factory=dict)  # hook file -> tool
    warnings: list[str] = field(default_factory=list)


def base_context(templates: Templates, config: Config, tool: str | None) -> dict:
    tool_def = templates.manifest["tools"].get(tool, {}) if tool else {}
    context = {
        "system": {"name": SYSTEM, "version": templates.version},
        "tool": {"id": tool or "none", **{k: v for k, v in tool_def.items() if not isinstance(v, (dict, list))}},
        "project": config.project,
        "commands": config.commands,
        "vars": config.variables,
    }
    context["partials"] = {}
    for key, text in templates.partials.items():
        context["partials"][key] = render(text, context, tool, f"partial {key}").strip("\n")
    return context


def extension_text(project: Path, relative: str, context: dict, tool: str) -> str:
    path = project / relative
    if not path.is_file():
        return ""
    body = render(path.read_text(encoding="utf-8"), context, tool, relative).strip()
    if not body:
        return ""
    return (
        "## Project-specific additions\n\n"
        f"Maintained in `{relative}`. They add to the baseline above or tighten it. "
        "An exception to a K policy needs an ADR (P §1.1).\n\n"
        f"{body}\n"
    )


def with_extensions(body: str) -> str:
    if "{{project_extensions}}" in body:
        return body
    return body.rstrip("\n") + "\n\n{{project_extensions}}\n"


def roster_text(component: Component) -> str:
    """The one-line summary, or the description's first sentence when a component has no summary."""
    if component.meta.get("summary"):
        return component.meta["summary"]
    description = component.meta["description"].strip()
    return re.split(r"(?<=[.!?])\s", description, maxsplit=1)[0]


def skill_roster(skills: list[Component], context: dict, tool: str) -> str:
    prefix = context["tool"]["skill_prefix"]
    rows = ["| Skill | Use it for |", "|---|---|"]
    for skill in skills:
        marker = " (project)" if skill.origin == "local" else ""
        text = render(roster_text(skill), context, tool, skill.label)
        rows.append(f"| `{prefix}{skill.name}`{marker} | {md_cell(text)} |")
    return "\n".join(rows)


def agent_roster(agents: list[Component], context: dict, tool: str) -> str:
    rows = ["| Agent | Stage | Use it for |", "|---|---|---|"]
    for agent in agents:
        marker = " (project)" if agent.origin == "local" else ""
        text = render(roster_text(agent), context, tool, agent.label)
        rows.append(f"| `{agent.name}`{marker} | {md_cell(agent.meta.get('stage', ''))} | {md_cell(text)} |")
    return "\n".join(rows)


def routes_table(config: Config, context: dict, tool: str) -> str:
    if not config.routes:
        return f"None configured. Add `[[routes]]` entries to `{CONFIG_REL}` to insert project-specific stages."
    rows = ["| When | Dispatch | After | Gate |", "|---|---|---|---|"]
    for index, route in enumerate(config.routes, 1):
        cell = {key: md_cell(render(str(route[key]), context, tool, f"{CONFIG_REL} route {index}"))
                for key in ("trigger", "agent", "after", "gate")}
        rows.append(f"| {cell['trigger']} | `{cell['agent']}` | {cell['after']} | {cell['gate']} |")
    return "\n".join(rows)


def agent_skills_text(agent: Component, config: Config, context: dict, tool: str) -> str:
    names = agent_skill_names(agent, config)
    if not names:
        return "No skills are assigned to this agent."
    if tool == "claude":
        listed = ", ".join(f"`{name}`" for name in names)
        return f"These skills are preloaded into your context. Follow them: {listed}."
    skills_dir = context["tool"]["skills_dir"]
    lines = ["Before you start, read each of these skills and follow it:", ""]
    lines.extend(f"- `{skills_dir}/{name}/SKILL.md`" for name in names)
    return "\n".join(lines)


def build_plan(project: Path, templates: Templates, config: Config) -> Plan:
    plan = Plan()
    agents, skills = select_components(templates, config, project)
    for target, relative in templates.manifest.get("managed", {}).items():
        inside(project, target)
        plan.files[target] = (templates.root / relative).read_bytes()  # copied verbatim, never rendered
    plan.files[ENGINE_REL] = templates.engine.read_bytes()

    for tool in config.tools:
        tool_def = templates.manifest["tools"][tool]
        context = base_context(templates, config, tool)
        context["roster"] = agent_roster(agents, context, tool)
        context["skill_roster"] = skill_roster(skills, context, tool)
        context["project_routes"] = routes_table(config, context, tool)
        context["project_extensions"] = extension_text(project, f"{EXTENSIONS_REL}/orchestrator.md", context, tool)
        block = render(with_extensions(templates.orchestrator), context, tool, "orchestrator")
        block = normalize_text(block)
        limit = tool_def.get("instructions_max_bytes")
        if limit and len(block.encode()) > limit * 0.6:
            plan.warnings.append(
                f"{tool_def['instructions']}: the orchestrator block is {len(block.encode())} bytes; "
                f"{tool_def['name']} reads at most {limit} bytes of project instructions"
            )
        plan.blocks[tool_def["instructions"]] = block
        plan.hooks[tool_def["hook_file"]] = tool

        for agent in agents:
            ext_rel = f"{EXTENSIONS_REL}/agents/{agent.name}.md"
            agent_context = {
                **context,
                "component": {"name": agent.name},
                "agent_skills": agent_skills_text(agent, config, context, tool),
                "project_extensions": extension_text(project, ext_rel, context, tool) if agent.origin == "template" else "",
            }
            body = normalize_text(render(with_extensions(agent.body), agent_context, tool, str(agent.source)))
            description = render(agent.meta["description"], context, tool, agent.label).strip()
            meta = tool_meta(agent, config, tool)
            note = f"{GENERATED_NOTE}; extend it in {ext_rel}."
            if tool == "claude":
                plan.files[f"{tool_def['agents_dir']}/{agent.name}.md"] = render_claude_agent(
                    agent, description, meta, agent_skill_names(agent, config), body, note, plan
                ).encode()
            else:
                plan.files[f"{tool_def['agents_dir']}/{agent.name}.toml"] = render_codex_agent(
                    agent, description, meta, body, note, plan
                ).encode()

        for skill in skills:
            ext_rel = f"{EXTENSIONS_REL}/skills/{skill.name}.md"
            skill_context = {
                **context,
                "component": {"name": skill.name},
                "project_extensions": extension_text(project, ext_rel, context, tool) if skill.origin == "template" else "",
            }
            base = f"{tool_def['skills_dir']}/{skill.name}"
            description = render(skill.meta["description"], context, tool, skill.label).strip()
            body = normalize_text(render(with_extensions(skill.body), skill_context, tool, str(skill.source / "SKILL.md")))
            meta = tool_meta(skill, config, tool)
            note = f"<!-- {GENERATED_NOTE}; extend it in {ext_rel}. -->"
            if tool == "claude":
                if re.search(r"\$(?:[0-9]|ARGUMENTS\b)", body) and "arguments" not in meta and "argument-hint" not in meta:
                    plan.warnings.append(f"{base}/SKILL.md: '$<digit>' or $ARGUMENTS is substituted by Claude Code")
                plan.files[f"{base}/SKILL.md"] = render_claude_skill(skill, description, meta, body, note, plan).encode()
            else:
                plan.files[f"{base}/SKILL.md"], openai_yaml = render_codex_skill(skill, description, meta, body, note, plan)
                if openai_yaml:
                    plan.files[f"{base}/agents/openai.yaml"] = openai_yaml
            for support in sorted(skill.source.rglob("*")):
                relative = support.relative_to(skill.source)
                if support.is_dir() or support.is_symlink() or relative.as_posix() == "SKILL.md":
                    continue
                if IGNORED_NAMES.intersection(relative.parts) or support.suffix == ".pyc":
                    continue
                if support.suffix == ".md":
                    text = render(support.read_text(encoding="utf-8"), skill_context, tool, str(support))
                    plan.files[f"{base}/{relative.as_posix()}"] = normalize_text(text).encode()
                else:
                    plan.files[f"{base}/{relative.as_posix()}"] = support.read_bytes()

    for relative in (*plan.files, *plan.blocks, *plan.hooks):
        inside(project, relative)
    return plan


def unknown_keys(component: Component, meta: dict, allowed: tuple, tool: str, plan: Plan) -> None:
    unknown = sorted(set(meta) - set(allowed))
    if unknown:
        plan.warnings.append(f"{component.label}: ignored {tool} keys {unknown}")


def render_claude_agent(agent, description, meta, skills, body, note, plan) -> str:
    unknown_keys(agent, meta, CLAUDE_AGENT_KEYS, "claude", plan)
    front = {"name": agent.name, "description": description}
    for key in CLAUDE_AGENT_KEYS:
        if key in meta:
            value = meta[key]
            front[key] = ", ".join(value) if key in ("tools", "disallowedTools") and isinstance(value, list) else value
    if skills:
        front["skills"] = skills
    return f"---\n{yaml_mapping(front)}---\n\n<!-- {note} -->\n\n{body}"


def render_codex_agent(agent, description, meta, body, note, plan) -> str:
    unknown_keys(agent, meta, CODEX_AGENT_KEYS, "codex", plan)
    lines = [f"# {note}", f"name = {toml_string(agent.name)}", f"description = {toml_string(description)}"]
    for key in CODEX_AGENT_KEYS:
        if key in meta:
            lines.append(f"{key} = {toml_value(meta[key])}")
    lines.append(f"developer_instructions = {toml_multiline(body)}")
    text = "\n".join(lines) + "\n"
    parsed = tomllib.loads(text)
    if parsed["developer_instructions"] != body or parsed["description"] != description:
        raise SyncError(f"{agent.label}: Codex TOML did not round-trip; report this as an engine defect")
    return text


def render_claude_skill(skill, description, meta, body, note, plan) -> str:
    unknown_keys(skill, meta, CLAUDE_SKILL_KEYS, "claude", plan)
    front = {"name": skill.name, "description": description}
    front.update({key: meta[key] for key in CLAUDE_SKILL_KEYS if key in meta})
    return f"---\n{yaml_mapping(front)}---\n\n{note}\n\n{body}"


def render_codex_skill(skill, description, meta, body, note, plan) -> tuple[bytes, bytes | None]:
    unknown_keys(skill, meta, CODEX_SKILL_KEYS, "codex", plan)
    front = {"name": skill.name, "description": description}
    if skill.meta.get("summary"):
        front["metadata"] = {"short-description": skill.meta["summary"]}
    openai = {}
    if "display_name" in meta:
        openai["interface"] = {"display_name": meta["display_name"]}
        if skill.meta.get("summary"):
            openai["interface"]["short_description"] = skill.meta["summary"]
    if "allow_implicit_invocation" in meta:
        openai["policy"] = {"allow_implicit_invocation": bool(meta["allow_implicit_invocation"])}
    skill_md = f"---\n{yaml_mapping(front)}---\n\n{note}\n\n{body}".encode()
    return skill_md, (yaml_mapping(openai).encode() if openai else None)


# --------------------------------------------------------------------------------------------------
# Applying a plan


@dataclass
class Change:
    action: str  # "write", "delete"
    target: str
    kind: str  # "file", "block", "hook"
    content: bytes | None = None
    backup: bool = False
    detail: str = ""


def load_lock(project: Path) -> dict | None:
    path = project / LOCK_REL
    if not path.exists() and not path.is_symlink():
        return None
    if not path.is_file():
        raise SyncError(f"{LOCK_REL}: expected a regular file")
    try:
        lock = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise SyncError(f"{LOCK_REL}: unreadable ({error})") from error
    if not isinstance(lock, dict) or lock.get("system") != SYSTEM:
        raise SyncError(f"{LOCK_REL}: not a {SYSTEM} lock")
    if lock.get("schema") != 1:
        raise SyncError(f"{LOCK_REL}: schema must be 1")
    for key in ("files", "blocks", "layout"):
        require_mapping(lock.get(key, {}), f"{LOCK_REL}: {key}")
    for key in ("tools", "hooks"):
        values = require_list(lock.get(key, []), f"{LOCK_REL}: {key}")
        if any(not isinstance(value, str) for value in values):
            raise SyncError(f"{LOCK_REL}: {key} must contain strings")
    for key in ("files", "blocks"):
        if any(not isinstance(target, str) or not isinstance(digest, str)
               for target, digest in lock.get(key, {}).items()):
            raise SyncError(f"{LOCK_REL}: {key} must map paths to hashes")
    if lock.get("source") is not None and not isinstance(lock["source"], str):
        raise SyncError(f"{LOCK_REL}: source must be a string")
    return lock


def replace_block(text: str | None, block: str | None) -> str | None:
    text = text or ""
    managed = f"{BLOCK_BEGIN}\n{block}{BLOCK_END}\n" if block is not None else ""
    if BLOCK_RE.search(text):
        updated = BLOCK_RE.sub(lambda _: managed, text, count=1)
    elif block is None:
        updated = text
    else:
        updated = managed if not text.strip() else text.rstrip("\n") + "\n\n" + managed
    if block is None and updated.strip():
        updated = updated.rstrip("\n") + "\n"
    return updated if updated.strip() else None


def current_block(text: str | None) -> str | None:
    matches = list(BLOCK_RE.finditer(text or ""))
    if len(matches) > 1:
        raise SyncError("instruction file contains more than one rust-delivery managed block")
    return matches[0].group(1) if matches else None


def merge_hook(text: str | None, command: str | None, target: str) -> str | None:
    try:
        data = json.loads(text) if text and text.strip() else {}
    except json.JSONDecodeError as error:
        raise SyncError(f"{target}: invalid JSON ({error}); fix it so the SessionStart hook can be registered") from error
    if not isinstance(data, dict):
        raise SyncError(f"{target}: expected a JSON object")
    hooks = require_mapping(data.get("hooks", {}), f"{target}: hooks")
    groups = require_list(hooks.get("SessionStart", []), f"{target}: hooks.SessionStart")

    validated = []
    ours = []
    for group_index, value in enumerate(groups, 1):
        group = require_mapping(value, f"{target}: SessionStart group {group_index}")
        handlers = require_list(group.get("hooks", []), f"{target}: SessionStart group {group_index} hooks")
        for handler_index, item in enumerate(handlers, 1):
            handler = require_mapping(
                item, f"{target}: SessionStart group {group_index} hook {handler_index}"
            )
            hook_text = str(handler.get("command", ""))
            if HOOK_MARKER in hook_text and "session-start" in hook_text:
                ours.append((group, handler))
        validated.append((group, handlers))

    desired = {"type": "command", "command": command, "timeout": HOOK_TIMEOUT} if command else None
    if desired and len(ours) == 1 and ours[0][1] == desired and ours[0][0].get("matcher") == HOOK_MATCHER:
        return text
    if not desired and not ours:
        return text
    kept = []
    for group, handlers in validated:
        remaining = [handler for handler in handlers if not any(handler is own for _, own in ours)]
        if remaining:
            kept.append({**group, "hooks": remaining})
    if desired:
        kept.append({"matcher": HOOK_MATCHER, "hooks": [desired]})
    if kept:
        hooks["SessionStart"] = kept
    else:
        hooks.pop("SessionStart", None)
    if hooks:
        data["hooks"] = hooks
    else:
        data.pop("hooks", None)
    if not data:
        return None
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def optional_bytes(path: Path, target: str) -> bytes | None:
    if not path.exists() and not path.is_symlink():
        return None
    if not path.is_file():
        raise SyncError(f"{target}: expected a regular file")
    try:
        return path.read_bytes()
    except OSError as error:
        raise SyncError(f"{target}: unreadable ({error})") from error


def optional_text(path: Path, target: str) -> str | None:
    data = optional_bytes(path, target)
    if data is None:
        return None
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError as error:
        raise SyncError(f"{target}: expected UTF-8 text ({error})") from error


def diff_plan(project: Path, plan: Plan, lock: dict | None) -> list[Change]:
    lock = lock or {}
    locked_files, locked_blocks = lock.get("files", {}), lock.get("blocks", {})
    changes: list[Change] = []
    for target, content in sorted(plan.files.items()):
        path = inside(project, target)
        current = optional_bytes(path, target)
        if current == content:
            continue
        edited = current is not None and sha256(current) != locked_files.get(target)
        changes.append(Change("write", target, "file", content, backup=edited,
                              detail="replaces a hand-edited or unmanaged file" if edited else ""))
    for target, digest in sorted(locked_files.items()):
        if target in plan.files:
            continue
        path = inside(project, target)
        current = optional_bytes(path, target)
        if current is not None:
            edited = sha256(current) != digest
            changes.append(Change("delete", target, "file", backup=edited, detail="no longer generated"))
    for target in sorted(set(plan.blocks) | set(locked_blocks)):
        path = inside(project, target)
        text = optional_text(path, target)
        block = plan.blocks.get(target)
        existing = current_block(text)
        if existing == block:
            continue
        updated = replace_block(text, block)
        if updated == text:
            continue
        edited = existing is not None and sha256(existing.encode()) != locked_blocks.get(target)
        action = "write" if updated is not None else "delete"
        changes.append(Change(action, target, "block", updated.encode() if updated is not None else None,
                              backup=edited, detail="orchestrator block"))
    hook_targets = set(plan.hooks) | set(lock.get("hooks", []))
    for target in sorted(hook_targets):
        path = inside(project, target)
        text = optional_text(path, target)
        tool = plan.hooks.get(target)
        updated = merge_hook(text, hook_command(tool) if tool else None, target)
        if updated == text:
            continue
        action = "write" if updated is not None else "delete"
        changes.append(Change(action, target, "hook", updated.encode() if updated is not None else None,
                              detail="SessionStart hook"))
    return changes


def apply_changes(project: Path, plan: Plan, changes: list[Change], templates: Templates, config: Config) -> str | None:
    stamp, backup_root = utc_stamp(), None
    for change in changes:
        path = inside(project, change.target)
        if change.backup and path.is_file():
            backup_root = project / BACKUPS_REL / stamp
            destination = backup_root / change.target
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, destination)
        if change.action == "write":
            atomic_write(path, change.content, executable=change.target == ENGINE_REL)
        elif path.is_file():
            path.unlink()
            prune_empty_dirs(project, path.parent)
    lock = {
        "schema": 1,
        "system": SYSTEM,
        "version": templates.version,
        "source": os.path.relpath(templates.root, project),
        "tools": config.tools,
        "files": {target: sha256(content) for target, content in sorted(plan.files.items())},
        "blocks": {target: sha256(block.encode()) for target, block in sorted(plan.blocks.items())},
        "hooks": sorted(plan.hooks),
        "layout": {tool: {key: templates.manifest["tools"][tool][key] for key in ("agents_dir", "skills_dir")}
                   for tool in config.tools},
        "synced_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
    }
    atomic_write(project / LOCK_REL, (json.dumps(lock, indent=2) + "\n").encode())
    return os.path.relpath(backup_root, project) if backup_root else None


def prune_empty_dirs(project: Path, directory: Path) -> None:
    stop = {project.resolve(), (project / DELIVERY_DIR).resolve()}
    while directory.resolve() not in stop and directory.is_dir() and not any(directory.iterdir()):
        directory.rmdir()
        directory = directory.parent


def lock_is_stale(lock: dict | None, plan: Plan, templates: Templates, config: Config) -> bool:
    if not lock:
        return True
    return (
        lock.get("version") != templates.version
        or lock.get("tools") != config.tools
        or set(lock.get("files", {})) != set(plan.files)
        or set(lock.get("blocks", {})) != set(plan.blocks)
        or set(lock.get("hooks", [])) != set(plan.hooks)
        or any(lock["files"].get(t) != sha256(c) for t, c in plan.files.items())
        or any(lock["blocks"].get(t) != sha256(b.encode()) for t, b in plan.blocks.items())
    )


@contextlib.contextmanager
def project_mutex(project: Path):
    path = project / MUTEX_REL
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "a+") as handle:
        try:
            import fcntl
        except ImportError:  # Windows without WSL: no advisory locks; syncs rarely overlap
            yield
            return
        deadline = time.monotonic() + 20
        while True:
            try:
                fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
                break
            except BlockingIOError:
                if time.monotonic() > deadline:
                    raise SyncError(f"another sync holds {MUTEX_REL}") from None
                time.sleep(0.1)
        try:
            yield
        finally:
            fcntl.flock(handle, fcntl.LOCK_UN)


@dataclass
class Outcome:
    changes: list[Change]
    warnings: list[str]
    backup: str | None
    applied: bool
    previous_version: str | None
    version: str


def run_sync(project: Path, templates: Templates, dry_run: bool = False, adopt_pinned: bool = True) -> Outcome:
    with project_mutex(project):
        lock = load_lock(project)
        config = load_config(project, templates)
        plan = build_plan(project, templates, config)
        changes = diff_plan(project, plan, lock)
        stale = lock_is_stale(lock, plan, templates, config)
        apply = not dry_run and (adopt_pinned or config.mode == "auto") and (changes or stale)
        backup = apply_changes(project, plan, changes, templates, config) if apply else None
        return Outcome(changes, plan.warnings, backup, bool(apply), (lock or {}).get("version"), templates.version)


def describe(changes: list[Change]) -> list[str]:
    lines = []
    for change in changes:
        verb = {"write": "update", "delete": "remove"}[change.action]
        extra = f" ({change.detail})" if change.detail else ""
        lines.append(f"  {verb:<7} {change.target}{extra}")
    return lines


# --------------------------------------------------------------------------------------------------
# Commands


def resolve_project(argument: str | None) -> Path:
    if argument:
        return Path(argument).resolve()
    own = Path(__file__).resolve()
    if own.parent.name == DELIVERY_DIR and own.name == "sync.py":
        return own.parent.parent
    return Path.cwd().resolve()


def require_templates(project: Path | None, lock: dict | None = None) -> Templates:
    root = find_templates(project, lock) if project else None
    if root is None:
        own = Path(__file__).resolve().parent.parent
        root = own if is_templates_root(own) else None
    if root is None:
        raise SyncError(
            f"templates not found; set {TEMPLATES_ENV} to the workspace templates folder, "
            "or run the engine from templates/delivery/sync.py"
        )
    return load_templates(root)


def cmd_install(args) -> int:
    project = Path(args.project).resolve()
    if not project.is_dir():
        raise SyncError(f"{project}: not a directory; create the project folder first")
    templates = require_templates(project)
    if project == templates.root or project.is_relative_to(templates.root):
        raise SyncError(f"{project}: is inside the templates folder; install into a project")
    tools = [tool.strip() for tool in args.tools.split(",") if tool.strip()]
    if not tools or any(tool not in TOOLS for tool in tools) or len(tools) != len(set(tools)):
        raise SyncError(f"--tools must be a duplicate-free, comma-separated subset of {','.join(TOOLS)}")
    name = args.name or project.name
    seeded = []
    for target, relative in templates.manifest.get("seeds", {}).items():
        path = inside(project, target)
        if path.exists():
            continue
        text = (templates.root / relative).read_text(encoding="utf-8")
        text = text.replace("{{project.name}}", name).replace("{{sync.tools}}", ", ".join(json.dumps(t) for t in tools))
        atomic_write(path, text.encode())
        seeded.append(target)
    outcome = run_sync(project, templates)
    print(f"{SYSTEM} {templates.version} installed into {project}")
    for target in seeded:
        print(f"  seed    {target}")
    print("\n".join(describe(outcome.changes)))
    report_tail(outcome)
    print(
        "\nNext:\n"
        f"  - Review {CONFIG_REL}: project name, commands, and which tools to generate.\n"
        "  - Start a new Claude Code or Codex session in the project folder. Directories created by this\n"
        "    install are only watched by sessions that start after it.\n"
        "  - Codex asks you to trust the project's SessionStart hook once: review it with /hooks.\n"
        f"  - Commit the generated files with the project; they let a clone work without the templates."
    )
    return 0


def cmd_sync(args) -> int:
    project = resolve_project(args.project)
    lock = load_lock(project)
    if lock is None:
        raise SyncError(f"{project}: {SYSTEM} is not installed; run install first")
    templates = require_templates(project, lock)
    outcome = run_sync(project, templates, dry_run=args.dry_run)
    heading = "would change" if args.dry_run else "changed"
    if outcome.changes:
        print(f"{SYSTEM} {outcome.previous_version} -> {outcome.version}: {heading} {len(outcome.changes)} file(s) in {project}")
        print("\n".join(describe(outcome.changes)))
    else:
        print(f"{SYSTEM} {outcome.version}: {project} is up to date")
    report_tail(outcome)
    return 0


def report_tail(outcome: Outcome) -> None:
    if outcome.backup:
        print(f"Hand edits were backed up to {outcome.backup}. Move lasting changes into {EXTENSIONS_REL}/.")
    for warning in outcome.warnings:
        print(f"warning: {warning}")


def report_interruption_checkpoint(project: Path) -> None:
    checkpoint = project / CHECKPOINT_REL
    if not checkpoint.is_file():
        return
    try:
        result = subprocess.run(
            [sys.executable, str(checkpoint), "status", "--hook"],
            cwd=project,
            capture_output=True,
            text=True,
            check=False,
            timeout=15,
        )
        if result.stdout:
            print(result.stdout, end="" if result.stdout.endswith("\n") else "\n")
        if result.returncode:
            detail = result.stderr.strip()
            suffix = f" ({detail})" if detail else ""
            print(f"{SYSTEM}: interruption checkpoint could not be read{suffix}; run "
                  f"python3 {CHECKPOINT_REL} status for details.")
    except (OSError, subprocess.TimeoutExpired) as error:
        print(f"{SYSTEM}: interruption checkpoint check failed: {error}.")


def cmd_session_start(args) -> int:
    if not sys.stdin.isatty():
        with contextlib.suppress(Exception):
            sys.stdin.read()
    project = None
    try:
        project = resolve_project(args.project)
        lock = load_lock(project)
        if lock is None:
            return 0
        root = find_templates(project, lock)
        if root is None:
            return 0  # a clone without the workspace: the committed files stand alone
        templates_engine = root / read_toml(root / "manifest.toml")["system"]["engine"]
        running = Path(__file__).resolve()
        if (templates_engine.resolve() != running and not os.environ.get(REEXEC_ENV)
                and templates_engine.is_file() and templates_engine.read_bytes() != running.read_bytes()):
            os.environ[REEXEC_ENV] = "1"
            os.execv(sys.executable, [sys.executable, str(templates_engine), "session-start",
                                      "--tool", args.tool, "--project", str(project)])
        templates = load_templates(root)
        outcome = run_sync(project, templates, adopt_pinned=False)
        version_pending = outcome.previous_version != outcome.version
        if not outcome.changes and not outcome.applied and not version_pending:
            return 0
        tool_def = templates.manifest["tools"][args.tool]
        if not outcome.applied:
            print(f"{SYSTEM}: template {outcome.previous_version} -> {outcome.version} has "
                  f"{len(outcome.changes)} pending file change(s), but this project is pinned. Adopt them with "
                  f"`python3 {ENGINE_REL} sync`.")
            return 0
        if not outcome.changes:
            return 0
        print(f"{SYSTEM}: synced the agent system from the workspace templates "
              f"({outcome.previous_version} -> {outcome.version}).")
        print("\n".join(describe(outcome.changes)))
        if any(change.target == tool_def["instructions"] for change in outcome.changes):
            print(f"{tool_def['instructions']} changed after this session loaded it. Read it again before "
                  "orchestrating delivery work.")
        report_tail(outcome)
    except SyncError as error:
        print(f"{SYSTEM}: sync skipped: {error}. Run `python3 {ENGINE_REL} status` for details.")
    except Exception as error:  # a session must never fail because of this hook
        print(f"{SYSTEM}: sync skipped after an unexpected {type(error).__name__}: {error}.")
    finally:
        if project is not None:
            report_interruption_checkpoint(project)
    return 0


def drift(project: Path, lock: dict) -> list[str]:
    edited = []
    for target, digest in lock.get("files", {}).items():
        path = inside(project, target)
        data = optional_bytes(path, target)
        if data is None:
            edited.append(f"{target} (missing)")
        elif sha256(data) != digest:
            edited.append(f"{target} (edited)")
    for target, digest in lock.get("blocks", {}).items():
        path = inside(project, target)
        block = current_block(optional_text(path, target))
        if block is None:
            edited.append(f"{target} (block missing)")
        elif sha256(block.encode()) != digest:
            edited.append(f"{target} (block edited)")
    return edited


def cmd_status(args) -> int:
    project = resolve_project(args.project)
    lock = load_lock(project)
    if lock is None:
        print(f"{project}: {SYSTEM} is not installed")
        return 1
    print(f"project      {project}")
    print(f"installed    {lock.get('version')} (synced {lock.get('synced_at')})")
    root = find_templates(project, lock)
    edited = drift(project, lock)
    if root is None:
        print("templates    not found; the committed files are in use unchanged")
    else:
        templates = load_templates(root)
        config = load_config(project, templates)
        print(f"templates    {templates.version} at {root}")
        print(f"mode         {config.mode}; tools: {', '.join(config.tools)}")
        outcome = run_sync(project, templates, dry_run=True)
        print(f"pending      {len(outcome.changes)} change(s)")
        print("\n".join(describe(outcome.changes)) or "", end="\n" if outcome.changes else "")
        for warning in outcome.warnings:
            print(f"warning      {warning}")
        local_agents, local_skills = load_local_components(project)
        if local_agents or local_skills:
            print("local        " + ", ".join(c.label for c in (*local_agents, *local_skills)))
    extensions = sorted(p.relative_to(project).as_posix() for p in (project / EXTENSIONS_REL).rglob("*.md")) \
        if (project / EXTENSIONS_REL).is_dir() else []
    if extensions:
        print("extensions   " + ", ".join(extensions))
    for item in edited:
        print(f"hand edit    {item}")
    return 0


def cmd_verify(args) -> int:
    project = resolve_project(args.project)
    problems, notes = [], []
    lock = load_lock(project)
    if lock is None:
        print(f"FAIL  {LOCK_REL}: missing; {SYSTEM} is not installed")
        return 1
    problems.extend(f"{item}: differs from what the sync wrote" for item in drift(project, lock))
    layout = lock.get("layout", {})
    for target in lock.get("files", {}):
        path = project / target
        if not path.is_file():
            continue
        parent = Path(target).parent.as_posix()
        is_agent = {tool: parent == dirs.get("agents_dir") for tool, dirs in layout.items()}
        if is_agent.get("codex"):
            try:
                parsed = tomllib.loads(path.read_text(encoding="utf-8"))
            except tomllib.TOMLDecodeError as error:
                problems.append(f"{target}: invalid TOML ({error})")
                continue
            if not all(parsed.get(key) for key in ("name", "description", "developer_instructions")):
                problems.append(f"{target}: a Codex agent needs name, description, and developer_instructions")
        if is_agent.get("claude") or path.name == "SKILL.md":
            text = path.read_text(encoding="utf-8")
            head = text.split("\n---\n", 1)[0]
            if not text.startswith("---\n") or "\nname: " not in head or "\ndescription: " not in head:
                problems.append(f"{target}: frontmatter needs name and description")
    for target in lock.get("hooks", []):
        path = project / target
        text = path.read_text(encoding="utf-8") if path.is_file() else ""
        if HOOK_MARKER not in text:
            problems.append(f"{target}: the SessionStart hook is not registered")
    root = find_templates(project, lock)
    if root is None:
        notes.append("templates not found: currency against the templates was not checked")
    else:
        templates = load_templates(root)
        try:
            outcome = run_sync(project, templates, dry_run=True)
        except SyncError as error:
            problems.append(str(error))
        else:
            problems.extend(f"{c.target}: out of date with templates {templates.version}" for c in outcome.changes)
            for warning in outcome.warnings:
                notes.append(warning)
            if lock.get("version") != templates.version:
                problems.append(f"{LOCK_REL}: records {lock.get('version')}, templates are {templates.version}")
    for note in notes:
        print(f"note: {note}")
    for problem in problems:
        print(f"FAIL  {problem}")
    print(f"{len(problems)} finding(s) in {project}")
    return 1 if problems else 0


def cmd_sync_all(args) -> int:
    root = Path(args.root).resolve()
    status = 0
    for project in sorted(p for p in root.iterdir() if (p / LOCK_REL).is_file()):
        try:
            templates = require_templates(project, load_lock(project))
            outcome = run_sync(project, templates, dry_run=args.dry_run)
            verb = "would change" if args.dry_run else "changed"
            print(f"{project.name}: {verb} {len(outcome.changes)} file(s)")
            print("\n".join(describe(outcome.changes)) or "", end="\n" if outcome.changes else "")
            report_tail(outcome)
        except SyncError as error:
            print(f"{project.name}: FAIL {error}")
            status = 1
    return status


AGENT_STUB = """+++
name = "{name}"
description = "TODO: one or two sentences saying what this agent does and when the orchestrator should dispatch it."
summary = "TODO: one line for the orchestrator roster"
stage = "TODO: the board state or step this agent owns"
skills = []

[claude]
tools = ["Read", "Grep", "Glob", "Bash"]
model = "inherit"

[codex]
sandbox_mode = "read-only"
+++

# TODO: agent title

State the mission, the stage boundary (entry, exit, what it may write, what it never does), what to read
first, the procedure, and what it returns.

{{{{agent_skills}}}}

## Return

{{{{partials.result_packet}}}}
"""

SKILL_STUB = """+++
name = "{name}"
description = "TODO: what this skill does and exactly when to use it. Discovery depends on this line."
summary = "TODO: one line for the orchestrator roster"
+++

# TODO: skill title

The procedure, rules, and checklists this project needs. Keep it short; move long reference material into
supporting files next to this one and link them.
"""


def cmd_new(args) -> int:
    project = resolve_project(args.project)
    if not NAME_RE.match(args.name):
        raise SyncError(f"{args.name!r}: use lowercase words joined by hyphens")
    if args.kind == "agent":
        path = project / LOCAL_REL / "agents" / f"{args.name}.md"
        content = AGENT_STUB.format(name=args.name)
    else:
        path = project / LOCAL_REL / "skills" / args.name / "SKILL.md"
        content = SKILL_STUB.format(name=args.name)
    if path.exists():
        raise SyncError(f"{path.relative_to(project)}: already exists")
    atomic_write(path, content.encode())
    print(f"created {path.relative_to(project)}")
    print(f"Fill in the TODOs, then run `python3 {ENGINE_REL} sync`. To replace a template {args.kind} of the same")
    print(f"name, first set enabled = false for it in {CONFIG_REL}.")
    return 0


def cmd_check(args) -> int:
    root = Path(args.templates).resolve() if args.templates else Path(__file__).resolve().parent.parent
    problems, notes = [], []
    try:
        templates = load_templates(root)
    except SyncError as error:
        print(f"FAIL  {error}")
        return 1
    listed_agents = {c.source.resolve() for c in templates.agents}
    listed_skills = {c.source.resolve() for c in templates.skills}
    delivery = templates.engine.parent
    for path in sorted((delivery / "agents").glob("*.md")):
        if path.resolve() not in listed_agents:
            problems.append(f"{path.relative_to(root)}: agent source is not listed in manifest.toml")
    for path in sorted((delivery / "skills").glob("*/SKILL.md")):
        if path.parent.resolve() not in listed_skills:
            problems.append(f"{path.parent.relative_to(root)}: skill source is not listed in manifest.toml")
    registered_partials = {
        (root / relative).resolve() for relative in templates.manifest.get("partials", {}).values()
    }
    for path in sorted((delivery / "partials").glob("*")):
        if path.is_file() and path.resolve() not in registered_partials:
            problems.append(f"{path.relative_to(root)}: partial source is not listed in manifest.toml")
    registered_project_files = {
        (root / relative).resolve()
        for table in ("seeds", "managed")
        for relative in templates.manifest.get(table, {}).values()
    }
    for path in sorted((delivery / "project").glob("*")):
        if path.is_file() and path.resolve() not in registered_project_files:
            problems.append(f"{path.relative_to(root)}: project source is not listed in manifest.toml")
    orchestrator_source = (root / templates.manifest["orchestrator"]["source"]).resolve()
    for path in sorted((delivery / "orchestrator").glob("*.md")):
        if path.resolve() != orchestrator_source:
            problems.append(f"{path.relative_to(root)}: orchestrator source is not listed in manifest.toml")
    skill_names = {skill.name for skill in templates.skills}
    for agent in templates.agents:
        for name in agent.meta.get("skills", []):
            if name not in skill_names:
                problems.append(f"agent {agent.name}: skill {name!r} is not in the manifest")
        if not agent.meta.get("stage"):
            problems.append(f"agent {agent.name}: frontmatter needs a stage")
    for component in (*templates.agents, *templates.skills):
        if not component.meta.get("summary"):
            problems.append(f"{component.label}: frontmatter needs a one-line summary for the orchestrator roster")
    for component in (*templates.agents, *templates.skills):
        if "{{project_extensions}}" not in component.body:
            notes.append(f"{component.label}: no {{{{project_extensions}}}} slot; extensions will be appended at the end")
    if "{{project_extensions}}" not in templates.orchestrator:
        problems.append("orchestrator: needs a {{project_extensions}} slot")
    with tempfile.TemporaryDirectory(prefix="rust-delivery-check-") as directory:
        scratch = Path(directory)
        try:
            check_render(scratch, templates, problems, notes)
        except SyncError as error:
            problems.append(str(error))
    for note in notes:
        print(f"note: {note}")
    for problem in problems:
        print(f"FAIL  {problem}")
    print(f"{len(problems)} finding(s) in {root}")
    return 1 if problems else 0


def check_render(scratch: Path, templates: Templates, problems: list[str], notes: list[str]) -> None:
    """Render every component for every tool into an empty project with default configuration."""
    config = load_config(scratch, templates)
    plan = build_plan(scratch, templates, config)
    notes.extend(plan.warnings)
    for tool in TOOLS:
        tool_def = templates.manifest["tools"][tool]
        size = len(plan.blocks[tool_def["instructions"]].encode())
        notes.append(f"{tool_def['instructions']}: orchestrator block is {size} bytes")
    rendered = {**plan.files, **{target: block.encode() for target, block in plan.blocks.items()}}
    verbatim = set(templates.manifest.get("managed", {})) | {ENGINE_REL}
    leftovers = [t for t, c in rendered.items()
                 if t not in verbatim and t.endswith((".md", ".toml")) and re.search(rb"\{\{|\}\}", c)]
    problems.extend(f"{target}: rendered output still contains {{{{ or }}}}" for target in leftovers)
    print(f"rendered {len(plan.files)} files and {len(plan.blocks)} instruction blocks for {', '.join(TOOLS)}")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="sync.py", description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)
    check = sub.add_parser("check", help="validate the templates")
    check.add_argument("--templates", help="templates folder (default: the one containing this engine)")
    install = sub.add_parser("install", help="install into a project")
    install.add_argument("project")
    install.add_argument("--tools", default="claude,codex")
    install.add_argument("--name", help="project name for .delivery/project.toml (default: folder name)")
    sync = sub.add_parser("sync", help="render from the templates now")
    sync.add_argument("project", nargs="?")
    sync.add_argument("--dry-run", action="store_true")
    start = sub.add_parser("session-start", help="SessionStart hook entry point")
    start.add_argument("--tool", choices=TOOLS, required=True)
    start.add_argument("--project")
    status = sub.add_parser("status", help="show installation state")
    status.add_argument("project", nargs="?")
    verify = sub.add_parser("verify", help="fail unless installed, unedited, and current")
    verify.add_argument("project", nargs="?")
    sync_all = sub.add_parser("sync-all", help="sync every installed project under ROOT")
    sync_all.add_argument("root")
    sync_all.add_argument("--dry-run", action="store_true")
    new = sub.add_parser("new", help="scaffold a project-local agent or skill")
    new.add_argument("kind", choices=("agent", "skill"))
    new.add_argument("name")
    new.add_argument("project", nargs="?")
    args = parser.parse_args(argv)
    handlers = {
        "check": cmd_check, "install": cmd_install, "sync": cmd_sync, "session-start": cmd_session_start,
        "status": cmd_status, "verify": cmd_verify, "sync-all": cmd_sync_all, "new": cmd_new,
    }
    try:
        return handlers[args.command](args)
    except SyncError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
